# docker-compose.test.yml
version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
      - JWT_SECRET=test-secret
    command: npm run test
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  node_modules: