version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - NODE_ENV=test
    networks:
      - test-network

networks:
  test-network:
    driver: bridge