name: Docker CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert repository name to lowercase
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      # Tambahkan step untuk memeriksa versi Docker
      - name: Check Docker version
        run: docker --version

      # Tambahkan step untuk memeriksa versi Docker Compose
      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Modifikasi step untuk menjalankan test
      - name: Run tests in container
        run: |
          docker ps
          docker images
          # Pastikan mongodb environment variable tersedia
          echo "MONGODB_URI=mongodb://mongodb:27017/test" > .env
          # Jalankan docker-compose dengan verbose mode
          docker-compose -f docker-compose.test.yml up --exit-code-from app --verbose

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert repository name to lowercase
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.string.outputs.lowercase }}:latest
            ghcr.io/${{ steps.string.outputs.lowercase }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max